### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by HuyNguyenDePaul** [magnetarpulse/neurobazaar#23]
Add authentication to the trame server(s). Thinking of using tokens. I am not sure entirely; I will have to do some more research.

**Comment by genfuture** [comment]
I have already implemented csrf_token for authentication. We can use for that authentication. Check my branch.

**Comment by HuyNguyenDePaul** [comment]
Great! I will take a look at it today!

**Comment by genfuture** [comment]
Yes you can look into mange workspaces in template and views.py file. You can find it there.

**Comment by HuyNguyenDePaul** [comment]
I think this is done finally. Will wait before closing.

**Comment by HuyNguyenDePaul** [comment]
Closed for now.
